version: "3.6"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: "3.10"

x-default-volumes: &default_volumes
  volumes:
    - ./:/app

services:
  card-vault-app:
    build:
      context: .
      args:
        <<: *build_args
    image: "card_vault-manage:local"
    entrypoint: /bin/bash
    command: "-c 'flask db upgrade && flask run --host=0.0.0.0 --port=5000'"
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    <<: *default_volumes
    ports:
      - "8080:5000"
