name: Python Testing and Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests with coverage
      run: |
        pip install pytest-cov
        pytest --cov=card_vault tests/
      env:
        FLASK_APP: autoapp.py
        FLASK_DEBUG: 1
        FLASK_ENV: development
        DATABASE_NAME: cardvault
        BASIC_AUTH_USERNAME: john
        BASIC_AUTH_PASSWORD: doe

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
